version: "2"

engines:
  eslint:
    enabled: true

ratings:
  paths:
    - "client/src/**.(js|jsx)"

exclude_paths:
  - ".nyc_output"
  - "coverage"
  - "node_modules"
  - "client/__tests__"
  - "client/dist"
  - "client/public"
