export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SET_AUTH_WORKING = 'SET_AUTH_WORKING';
export const UNSET_AUTH_WORKING = 'UNSET_AUTH_WORKING';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const FETCHING_APP_COUNT = 'FETCHING_APP_COUNT';
export const LOADING = 'LOADING';
export const IS_FETCHING = 'IS_FETCHING';
export const IS_FETCHING_ERROR= 'IS_FETCHING_ERROR';
export const CLEAR_PARTY_ERROR = 'CLEAR_PARTY_ERROR';

// Party
export const ADD_PARTY_SUCCESS = 'ADD_PARTY_SUCCESS';
export const ADD_PARTY_FAILURE = 'ADD_PARTY_FAILURE';
export const EDIT_PARTY_SUCCESS = 'EDIT_PARTY_SUCCESS';
export const EDIT_PARTY_FAILURE = 'EDIT_PARTY_FAILURE';
export const DELETE_PARTY_SUCCESS = 'DELETE_PARTY_SUCCESS';
export const DELETE_PARTY_FAILURE = 'DELETE_PARTY_FAILURE';
export const GET_PARTIES_SUCCESS = 'GET_PARTIES_SUCCESS';
export const GET_PARTIES_FAILURE = 'GET_PARTIES_FAILURE';

// Office
export const ADD_OFFICE_SUCCESS = 'ADD_OFFICE_SUCCESS';
export const ADD_OFFICE_FAILURE = 'ADD_OFFICE_FAILURE';
export const EDIT_OFFICE_SUCCESS = 'EDIT_OFFICE_SUCCESS';
export const EDIT_OFFICE_FAILURE = 'EDIT_OFFICE_FAILURE';
export const DELETE_OFFICE_SUCCESS = 'DELETE_OFFICE_SUCCESS';
export const DELETE_OFFICE_FAILURE = 'DELETE_OFFICE_FAILURE';
export const GET_OFFICES_SUCCESS = 'GET_OFFICES_SUCCESS';
export const GET_OFFICES_FAILURE = 'GET_OFFICES_FAILURE';

export const ASPIRE_OFFICE_SUCCESS = 'ASPIRE_OFFICE_SUCCESS';
export const ASPIRE_OFFICE_FAILURE = 'ASPIRE_OFFICE_FAILURE';